setopt    ALIASES
setopt    ALL_EXPORT
setopt    ALWAYS_LAST_PROMPT
setopt    ALWAYS_TO_END
setopt    APPEND_HISTORY
setopt NO_AUTO_CD
setopt    AUTO_CONTINUE
setopt    AUTO_LIST
setopt    AUTO_MENU
setopt    AUTO_NAME_DIRS
setopt    AUTO_PARAM_KEYS
setopt    AUTO_PARAM_SLASH
setopt    AUTO_PUSHD
setopt NO_AUTO_REMOVE_SLASH
setopt    BAD_PATTERN
setopt    BANG_HIST
setopt    BASH_AUTO_LIST
setopt NO_BEEP
setopt NO_BSD_ECHO
setopt    BG_NICE
setopt    CHECK_JOBS
setopt NO_CLOBBER
setopt    COMPLETE_ALIASES
setopt    COMPLETE_IN_WORD
setopt NO_CORRECT_ALL
setopt    EQUALS
setopt    EXTENDED_HISTORY
setopt NO_FLOW_CONTROL
setopt    GLOB_COMPLETE
setopt    HASH_CMDS
setopt    HIST_REDUCE_BLANKS
setopt    HIST_FIND_NO_DUPS
setopt    HIST_IGNORE_DUPS
setopt    HIST_IGNORE_SPACE
setopt    HIST_SAVE_NO_DUPS
setopt NO_HUP
setopt    INTERACTIVE_COMMENTS
setopt    LIST_AMBIGUOUS
setopt    LIST_BEEP
setopt    LIST_PACKED
setopt    LIST_TYPES
setopt    MARK_DIRS
setopt    MULTIOS
setopt    NOTIFY
setopt    PRINT_EXIT_VALUE
setopt    PROMPT_SUBST
setopt    NO_RM_STAR_SILENT
setopt    SHORT_LOOPS
